stages:
  - lint
  - test
  - build
  - docker
  - deploy

variables:
  DOCKER_DRIVER: overlay2

lint:
  stage: lint
  script:
    - npm ci
    - npm run lint

test:
  stage: test
  script:
    - npm ci
    - npm run test -- --ci

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

docker:
  stage: docker
  image: docker:24.0
  services: [docker:24.0-dind]
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

deploy:
  stage: deploy
  environment: production
  script:
    - helm upgrade --install promanage ./devops/helm -f ./devops/helm/values.yaml --namespace promanage --create-namespace
  when: manual
